kind: ValidatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1beta1
metadata:
  name: opa-validating-webhook
webhooks:
  - name: validating-webhook.openpolicyagent.org
    rules:
      - operations: ["CREATE", "UPDATE", "DELETE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["*"]
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBekNDQWV1Z0F3SUJBZ0lKQVAxbXB3bzNyZmZETUEwR0NTcUdTSWIzRFFFQkN3VUFNQmN4RlRBVEJnTlYKQkFNTURHRmtiV2x6YzJsdmJsOWpZVEFnRncweE9UQXlNakl4TURFeE1UVmFHQTh5TWpreU1USXdOekV3TVRFeApOVm93RnpFVk1CTUdBMVVFQXd3TVlXUnRhWE56YVc5dVgyTmhNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DCkFROEFNSUlCQ2dLQ0FRRUEwTFAvSklGY0tNTkh3SHlIMUxoMnByTGlyNkdpbDI4aG5qaFdsUElMVmFFVkpMSHAKUUZFbmZWNm9lYmhINStkaTBrTXovUFNTN09LNGVOVWtPMUJ5TnQyMU5SNHdrMi9GTGRJMDdjc1YrQ00zQ2x3Ygo2Um5QQnJrdXJEek1SWlNwL3FvRE93RlZHWTVNYUx5NkpWQ1NFYlRGQk14RDRqclZnaExXMG9uK2NZb01pL25QCmY1aTBMd0ZYMktkQllqcWI1TVljMjVuUHdGcWpRdG1TazIxZW1tbnk2Z1VEYk1lRjB5NUZ3NUZybGNZblA3eHoKc3NSaCtMY2F3ekFrdVVxK0Z1SjVud2diNFBpUTYweWRlaHBmVng1cld6RHhkYVE5Rm5HR245cWkxTEFNU2pwVApETHZMcDJNckh0YWJSNFkwZTlIMW9DZmZaMGFiWFhua0VlSnpWUUlEQVFBQm8xQXdUakFkQmdOVkhRNEVGZ1FVCkdhempWTWRmc0dpOEtLRURNTzZ0dG5QRmdOVXdId1lEVlIwakJCZ3dGb0FVR2F6alZNZGZzR2k4S0tFRE1PNnQKdG5QRmdOVXdEQVlEVlIwVEJBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQXdrTzlpUFZEenlzWQpYdFh6U2Y4SThDZm9QV0RXU0VVYXdFL1BCRlF3bmxYTjVVQ2VBdVZsR0RhTEFCZklIYTRENk1wTzZyWlcxOTZ4Clh5UFYwRGpXNkd3ZDAvUkplNzFTeGZ1eXp1ZkhNazZHUjBaaHowNTZ6alhSTmQ4bjNQczVTMXJ0d2M1QXowaGcKV2FXMnN3R0VVdFpsUWFmbWdweVYrTWRiQjJNaTQ1RFF0UnlMU09XeXQ1TStBWkhWMGFRZzNxZFp6V09ReHZabworNVpCeXJKbFl3Y09YSHRsakJtRG1tZGFyd2tQMXZUaGhPZ0pSbkFENjJFOTJ3TzNYSEdSU0JpQ2phY095MTBVCjc5bHh0MnNTdXhTUkFyRWRpbmQxNHdRVENGeUd2cHVUWmdxSEFkd1NhTFRTN0lFVkxWdmJSdGZGQjVJRWNNRW8KUW5DeTFXVUtpdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        namespace: opa
        name: opa
